### ISSUE TITLE
[QUESTION] Console Application using Shared mode but got file is lock error.

### ISSUE THREAD

**Issue by alonstar** [mbdavid/LiteDB#1580] opened 2020-03-19 08:44 UTC
I'm using .NET Framework 4.7.2 and LiteDb 5.0.4, and I have three repository using the same connection string. 

I got a file is lock exception when using 5.0.4. (downgrade to 4.1.4 it's ok.)

        public static ConnectionString BuildConnectionString(string fileName)
        {
            var dir = Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "Database");
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var filePath = Path.Combine(dir, fileName + ".db");

            return new ConnectionString() { Filename = filePath, Connection = ConnectionType.Shared };
        }

Stacktrace:

	   於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   於 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   於 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
	   於 LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
	   於 System.Lazy`1.CreateValue()
	   於 System.Lazy`1.LazyInitValue()
	   於 LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32 memorySegmentSize)
	   於 LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
	   於 LiteDB.SharedEngine.OpenDatabase()
	   於 LiteDB.SharedEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
	   於 LiteDB.LiteCollection`1.EnsureIndex(String name, BsonExpression expression, Boolean unique)
	   於 TCG.TradingService.Repositories.StatusRepository..ctor() 於 D:\Projects\TradingService\Repositories\StatusRepository.cs: 行 13

**Comment by lbnascimento** [comment] 2020-03-19 14:48
@alonstar Are you accessing the same datafile from multiple processes?

**Comment by nightroman** [comment] 2020-03-19 15:44
Is this the reason of the problem, perhaps?

*LiteDB\Engine\Disk\StreamFactory\FileStreamFactory.cs*

```csharp
        public Stream GetStream(bool canWrite, bool sequencial)
        {
            var write = canWrite && (_readonly == false);

            var isNewFile = write && this.Exists() == false;

            var stream = new FileStream(_filename,
                _readonly ? System.IO.FileMode.Open : System.IO.FileMode.OpenOrCreate,
                write ? FileAccess.ReadWrite : FileAccess.Read,
                write ? FileShare.Read : FileShare.ReadWrite,
                PAGE_SIZE,
                sequencial ? FileOptions.SequentialScan : FileOptions.RandomAccess);
```

The 3rd parameter is `FileAccess`. When `write` is true then we require `FileAccess.ReadWrite`.

The 4th parameter is `FileShare`. When `write` is true then we only allow `FileShare.Read` for others.

Now, imagine the second process is doing the same shortly after the first. It tries to get `FileAccess.ReadWrite` but it cannot because the first process only allows `Read` for others.

**Comment by nightroman** [comment] 2020-03-19 17:06
I tried to reproduce the similar (maybe) scenario using [Ldbc](https://github.com/nightroman/Ldbc) and the following PowerShell script:

```powershell
Import-Module Ldbc

Use-LiteDatabase 'Filename=z.LiteDB; Connection=Shared' {
    $test = Get-LiteCollection Test
    $test.EnsureIndex('x', 'x', $false)
    Read-Host Enter
}
```

**Steps:**

- run one instance of the script in a console
    - it prints "Enter" in order to continue, do not press yet
- run another instance of the script in another console
    - it "hangs" forever, i.e. "Enter" is not printed
- press "Enter" in the first script console
    - the first script finishes
    - the second script is unlocked and prints "Enter"
    
**Question:**

Is this how it should work? Both databases are opened "Shared".

P.S. Sorry if this is off-topic but I think this might be related.
(and also I tried to reproduce the original problem, as far as we do not have enough info from OP)

**Comment by lbnascimento** [comment] 2020-03-19 17:42
@alonstar @nightroman Could you test with the latest commit? (it appears to have been a silly copy/paste mistake)

**Comment by nightroman** [comment] 2020-03-19 17:47
@lbnascimento My script works now without unexpected locks. Great!
(as usual, I looking forward for the updated package, please...)

**Comment by alonstar** [comment] 2020-03-23 03:42
> @alonstar Are you accessing the same datafile from multiple processes?

No, I use the same process and multiple threads. The latest commit is work, but I got System.NullReferenceException when inserting data...T_T

	   於 LiteDB.BsonValue.GetHashCode() 於 D:\Projects\LiteDB\LiteDB\Document\BsonValue.cs: 行 561
	   於 System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
	   於 System.Linq.Set`1.InternalGetHashCode(TElement value)
	   於 System.Linq.Set`1.Find(TElement value, Boolean add)
	   於 System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
	   於 LiteDB.BsonExpression.<GetIndexKeys>d__58.MoveNext() 於 D:\Projects\LiteDB\LiteDB\Document\Expression\BsonExpression.cs: 行 216
	   於 LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data) 於 D:\Projects\LiteDB\LiteDB\Engine\Engine\Insert.cs: 行 80
	   於 LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction) 於 D:\Projects\LiteDB\LiteDB\Engine\Engine\Insert.cs: 行 33
	   於 LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn) 於 D:\Projects\LiteDB\LiteDB\Engine\Engine\Transaction.cs: 行 101
	   於 LiteDB.SharedEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId) 於 D:\Projects\LiteDB\LiteDB\Client\Shared\SharedEngine.cs: 行 199
	   於 LiteDB.LiteCollection`1.Insert(T entity) 於 D:\Projects\LiteDB\LiteDB\Client\Database\Collections\Insert.cs: 行 22

**Comment by alonstar** [comment] 2020-03-23 03:49
And another, I tried using old db with upgrade, but got  System.MissingMethodException: 找不到方法: 'Void LiteDB.ConnectionString.set_Upgrade(Boolean)'

**Comment by lbnascimento** [comment] 2020-03-23 14:15
@alonstar I'm going to close this issue, given that the original problem appears to be fixed. Could you open a new issue with more info (such as OS, LiteDB version and NET Framework/Core version) and some code I could use to reproduce this new issue?

**Closed by lbnascimento** 2020-03-23 14:15 UTC
Labels: question

**Comment by nightroman** [comment] 2020-03-23 14:23
@lbnascimento @mbdavid 
Any raw estimate of v5.0.5 release date?
