### ISSUE TITLE
Problem retrieving .net System.Drawing.Color from LiteDB

### ISSUE THREAD

**Issue by stigzler** [mbdavid/LiteDB#1369] opened 2019-11-24 22:05 UTC
Hi,

LiteDB seems to be having problems retrieving these values. Extract of my poco class:

```
Public Property ContentStretch As SetupWindow.ContentStretchMode = SetupWindow.ContentStretchMode.Stretch
    <Id(25, 10), Category("General"), DisplayName("Background Color"), Description("The window background colour. This can also include transparency.")>
    Public Property BackgroundColor As Color = Color.Lime
    <Id(30, 10), Category("General"), DisplayName("Window Type"), Description("Windowed of Fullscreen")>
    Public Property WindowType As SetupWindow.WindowTypes = SetupWindow.WindowTypes.Windowed
    <Id(35, 10), Category("General"), DisplayName("Topmost"), Description("Whether to place the window over all preceding windows")>
    Public Property Topmost As Boolean = False
```
If I explore the LiteDB - the color values all seem stored correctly:

![litedb1](https://user-images.githubusercontent.com/4856029/69502274-657a7a00-0f05-11ea-968b-775bcf8c1937.png)

However, when I retrieve from LiteDB, all other values are retrieved correctly, apart from the color object (which seems to be default black):

![litedb2](https://user-images.githubusercontent.com/4856029/69502365-48927680-0f06-11ea-8277-0b2216e799df.png)

I'd be grateful if you could advise as this one has me scratching my head!

**Comment by Tirraon** [comment] 2019-11-24 22:23
@stigzler 
You should try to register Color as custom type:
https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#register-a-custom-type

**Comment by nh43de** [comment] 2019-11-24 23:59
Have a feeling this is related to/duplicate of #1157

**Comment by stigzler** [comment] 2019-11-25 20:15
@Tirraon - thanks - I'll check this out, but to also address @nh43de 's point - it's puzzling because native LiteDB appears to Serialise drawing.color perfectly fine (if you see the db browser image at the top of this post). So just curios about why it doesn't deserialize them as well?

Your suggestion is a good backup though, @Tirraon - however - I'm interested in @mbdavid 's view on this too.

**Comment by stigzler** [comment] 2019-12-08 19:08
@mbdavid - hi - any ideas on this issue? I'm at a position where I need to start considering whether I take a workaround route via custom object or use LiteDB's inbuilt object parsing. I'd much rather use the latter!

**Comment by mbdavid** [comment] 2019-12-10 16:34
Hi @stigzler, fields like `R`, `G`, `B` in `Color` are readonly and can't be setted when deserialize. In this case, the best way is register a custom type;

**Comment by stigzler** [comment] 2019-12-10 19:40
@mbdavid - thanks for the reply. I do appreciate it as I'd imagine you get many requests whilst also developing this fine library. 

OK - I'll have a look into custom types

**Comment by JensSchadron** [comment] 2020-01-28 22:31
Given that this issue has been answered, I'll be closing the ticket. Feel free to reopen the ticket if you think that your question hasn't been fully resolved.

**Closed by JensSchadron** 2020-01-28 22:31 UTC
Labels: question, v4
