### ISSUE TITLE
Upsert Returns False on Update

### ISSUE THREAD

**Issue by henzard** [mbdavid/LiteDB#1410] opened 2020-01-22 19:10 UTC
Var _collection.Upsert(newItem) returns true, _collection.Upsert(item) doing a update returns false
I am expecting a false on no action

**Comment by lbnascimento** [comment] 2020-01-22 19:42
Hello!

Upsert returns true if it performs an insertion and false if it performs an update.

The documentation is being reviewed for v5.

**Comment by JensSchadron** [comment] 2020-01-23 22:32
Marked this ticket as duplicate as this "issue" is a duplicate of #1388. To keep the issue tracker a bit more manageable, I'll be closing this ticket.

**Closed by JensSchadron** 2020-01-23 22:32 UTC
Labels: documentation, duplicate
