### ISSUE TITLE
[BUG] Transactions are not removed in LiteDB 5.0.18

### ISSUE THREAD

**Issue by martijnboland** [mbdavid/LiteDB#2435] opened 2024-02-21 12:16 UTC
**Version**
5.0.18

**Describe the bug**
We use a single IDatabase  instance registered as singleton. Our application performs reads and writes from many different threads. After a little while, LiteDB starts throwing exceptions that the max number of transactions is reached. While inspecting TransactionMonitor, we only see an increasing number of transactions.

With 5.0.17 everything works fine and transactions are released properly.

**Code to Reproduce**
```
for (var i = 0; i < 110; i++)
{
    await Task.Run(() =>
    {
        try
        {
            var result = _collection.FindById(key);
        }
        catch (Exception ex)
        {
            // Do something with exception. After 100 iterations, the max number of transactions will be reached
        }
    });
}

```

**Expected behavior**
The code above should run without exception.

**Comment by icegothic** [comment] 2024-02-22 13:56
Hi, I also have a "Maximum number of transactions is reached." issue on my project with versions 5.0.18 & 5.0.19! Do I need to adapt my code in some way?

Note: version 5.0.17 works fine for me too.

**Comment by hizume** [comment] 2024-02-23 01:20
This problem occurs even in the case of a single thread.
It is reproduced in the following code:

```
static void Main()
{
    // Create a new database.
    using var database = new LiteDatabase("test.db");

    var collection = database.GetCollection("test");
    collection.Insert(new BsonDocument { ["_id"] = 1 });

    for (int i = 0; i < 101; i++)
    {
        try
        {
            collection.FindById(1);
        }
        catch (LiteException ex)
        {
            // An exception is thrown when i reaches 100.
            Console.WriteLine(ex.Message);
        }
    }
}
```

I will send a pull request to fix it.

**Comment by dgodwin1175** [comment] 2024-02-23 01:49
@mbdavid Assuming this fix has been tested and verified, can we get a new release that includes it?

**Comment by alexanderdibenedetto** [comment] 2024-04-01 22:21
Hi - what's the update on this? I see a PR linked as open. It would be good to get this issue fixed so we can update.

**Comment by kjetilgloppen** [comment] 2024-04-12 13:26
I saw the same issue when upgrading from 5.0.12 to 5.0.19. Version 5.0.17 is the only workable solution for now it seems...

**Comment by FelixLorenz** [comment] 2024-04-30 06:44
Hi together, are there any updates on this? Also still staying with 5.0.17 due to this issue

**Comment by PatrickSlamp** [comment] 2024-05-20 08:50
I have update on this issue. Not sure if this is the right spot to put it, but I noticed something with transactions not being removed. As shown in the image below when using FirstOrDefault the transaction is not removed, when using ToList() in my case fixed it. Maybe some with more elaborate knowledge of the library can confirm my suspicion.
![image](https://github.com/mbdavid/LiteDB/assets/146711770/a8694184-5d89-4f85-b1e1-e67de901ae3d)

**Comment by JKamsker** [comment] 2024-06-04 17:58
This issue has been addressed and fixed in the latest commit. 
A new release is coming shortly.
Reopen this issue or open a new one if this issue persists in the upcoming version please.

**Closed by JKamsker** 2024-06-04 17:58 UTC
Labels: bug
