### ISSUE TITLE
Linq expression fails

### ISSUE THREAD

**Issue by andreykalyta** [mbdavid/LiteDB#734] opened 2017-09-18 17:01 UTC
```
PaintingData data = col.FindOne (x => (x.imageName.ToString () == imageName && x.imageType == imageType) );
PaintingData data1 = col.FindOne (Query.Where("imageName", name => name.ToString() == imageName));
PaintingData data2 = col.FindOne (Query.And(Query.EQ("imageName", imageName), Query.EQ("imageType", imageType) ) );

List<PaintingData> data3 = col.Find (x => x.imageName.ToString () == imageName).Where( x => x.imageType == imageType ).Where(x => x.paintingIndex == paintingIndex).ToList();

```

@mbdavid  Hi! From those 4 expressions only data3 is not null and its count > 0. I use unity3d, net3.5

**Comment by mbdavid** [comment] 2017-09-29 19:24
Hi @andreykalyta, are you using LiteDB v4? Can you paste your document structure (class code) so I can check this.

**Comment by Roderik11** [comment] 2017-09-30 01:16
Completely different project, same problem:

`        var result1 = col.Find(x => x.Name.ToString() == "Sun").ToList();
        // count = 1

        var result2 = col.Find(x => x.Name == "Sun").ToList();
        // count = 0

        var result3 = col.Find(LiteDB.Query.EQ("Name", "Sun")).ToList();
        // count = 0
`
litedb 4.0 (cloned and built from git today). using it in Unity5.6

**Comment by Roderik11** [comment] 2017-09-30 01:43
I tried creating an index for Name, but it throws the index cant be larger than 512 bytes exception.

**Comment by mbdavid** [comment] 2017-09-30 01:54
Can you post all your code snippet with this error? I will try run here.

**Comment by Roderik11** [comment] 2017-09-30 01:58
Debugging in Unity:
Install Unity (get their install tool), make sure you also install the MS VisualStudio tools for Unity (part of the installer).
Create a new empty project.
Copy the LiteDB source folder into your project/Assets.
Create an "Editor" folder in your project (righclick in project panel).
Create a new C# script  "LiteDBTest" in that editor folder (rightclick -> C# script).
Double click the script, it should start Visual Studio.
Copy/paste this code:

        using UnityEditor;
        using LiteDB;
        using System.Linq;

        public class LiteDBTest
        {
            [MenuItem("LiteDB/Run Test")]
            static void RunTest()
            {
                using (var db = new LiteDatabase(@"C:\Temp\MyData.db"))
                {
                    var col = db.GetCollection<TestData>();
                    col.Insert(new TestData { Name = "First" });

                    var result1 = col.Find(x => x.Name.ToString() == "First").ToList();
                    var result2 = col.Find(x => x.Name == "First").ToList();
                    var result3 = col.Find(LiteDB.Query.EQ("$.Name", "First")).ToList();
                }
            }
        }

        public class TestData
        {
            public GUID ID { get; set; }
            public string Name { get; set; }
        }

Save the file. Go back to Unity.
In the main menu bar you should see a LiteDB entry now.
Hit F5 in Visual Studio and set a breakpoint in the RunTest method.
Go to Unity and click the LiteDB->Run Test.
Debug away!

**Comment by mbdavid** [comment] 2017-09-30 02:00
Ok, thanks. I will try here.

**Comment by Roderik11** [comment] 2017-09-30 02:29
Strangely in this example i can add an index for Name just fine, but in my project it throws "Index key must be less than 512 bytes.", altho in both cases the Name field is simply a string. (the class it fails on as Name, Name2, Name3, Name4)

**Comment by mbdavid** [comment] 2017-09-30 02:39
@Roderik11, it's very strange. Did you tried use dll version (net35 version)? When add LiteDB source to Unity project, compile variable are used? I'm still downloading unity stuff again, to try run your example

**Comment by Roderik11** [comment] 2017-09-30 02:41
Yeah i built the assembly and copied it over. But this way i cant step inside code.
You'd have to copy the source folder instead (and remove anything not compatible with 3.5).
Unity then compiles it for you.

**Comment by mbdavid** [comment] 2017-10-01 14:02
Hi @Roderik11, can you create a git repository with a Unity project with a simple example?

BTW, I'm thinking to remove .NET 3.5 support in final release of LiteDB v4. This final version will run only in v4 and NetStandard 2. But, before this, I will create a fork project exclusive to work in Unity (LiteDB.Unity). This new fork will run separately from main LiteDB project, and I will search for Unity community members to help me in this source. If you want help, will be super welcome 😄

**Comment by fitialovks** [comment] 2017-11-11 22:20
I have same problem with LiteDB 4.0.0 release and Unity3d 2017.2.

1. Unity "stable" runtime 3.5 is incompatible with either Release or Debug version of LiteDB for 3.5. Find returns no values. Even debugger is not working in VS2017.
2. LiteDB for either 3.5 or 4.0 appears to be working in Unity with experimental 4.6 runtime. Debugger steps into DLL code without any issues.

No idea what is going on. Luckily I can continue with 4.6 for now.

**Comment by fitialovks** [comment] 2017-11-11 22:40
I created a project that reproduces this issue: https://github.com/fitialovks/NoLiteDbForMe

**Comment by mbdavid** [comment] 2017-11-12 12:37
Hi @fitialovks, thanks for your code. This unity problem looks a difference between full net 3.5 and unity version. I created an issue in your repo to get some help to reproduce. 

I think the problem is on class serialization (BsonMapper class). I will try run first using only BsonDocument (with no mapper) do test if all engine are working as excepted.

**Comment by mbdavid** [comment] 2017-11-14 00:44
Hi guys, good news! After many hours re-writing LiteDB in Unity (like a CSI agent) I found a big issue in Unity3D regex method - doesn't work indexes. This simple expressions DO NOT WORK in Unity3D (but works fine in .NET 3.5/4/NETStandard)!!

`var match = regex.Match(this.Source, this.Index, this.Source.Length - this.Index);`

I "fixed" using a substring of `this.Source`. Using substring is much more slower than use direct indexes in Regex match method, but works. I'm attaching here compiled version of LiteDB for you guys can test better if now working as excepted.


[LiteDB_Unity.zip](https://github.com/mbdavid/LiteDB/files/1469149/LiteDB_Unity.zip)

**Comment by fitialovks** [comment] 2017-11-20 21:39
I tried to create a bug report for Unity team, but the regexp works for me. 
https://github.com/fitialovks/UnityRegexpBug/blob/master/Assets/Editor/RegexTest.cs
Could you have a look and correct my tests? Or does it need to be in a DLL?

**Comment by mbdavid** [comment] 2017-11-24 22:15
Hi @fitialovks, but in your example are you not using `^` and this make all difference (if you not use `^`  this pattern can be search in any place on string). 

```C#
string source = "1234567890";
int index = 3;
var regex = new Regex("^4");

// Substring here is: "4567890"
var match = regex.Match(source, index, source.Length - index);

// in Unity fail, in .NET3.5/4/Standard works
Assert.IsTrue(match.Success);
Assert.AreEqual("4", match.Value);
```

**Comment by lbnascimento** [comment] 2020-02-06 17:26
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-06 17:26 UTC
Labels: bug
