### ISSUE TITLE
[BUG] v5.0.4 ILiteCollection.Find() does not work with enum

### ISSUE THREAD

**Issue by hopson-2** [mbdavid/LiteDB#1589] opened 2020-03-23 21:24 UTC
**Version**
5.0.4/Windows 10/net framework 4.7,2

**Describe the bug**
the ILiteCollection.Find() method does not appear to work with enum

**Code to Reproduce**
LINQPad v5.41/C# Program

```C#
void Main()
{
	const string databaseFilename = @"C:\temp\litedb_504_test.db";
	using (LiteDB.ILiteDatabase liteDB= new LiteDatabase(databaseFilename))
	{
		ILiteCollection<Customer> collectionCustomer = liteDB.GetCollection<Customer>("Customer");
		liteDB.DropCollection("Customer"); //remove previous test customers from DB
		
		Customer doeJohn = new Customer()
		{
			Name="John Doe"
			, Description = "Test Customer"
			, PaymentMethod = PaymentMethodType.Cash
		};
		Customer doeJane = new Customer()
		{
			Name = "Jane Doe"
			, Description = "Test Customer 2"
			, PaymentMethod = PaymentMethodType.CreditCard
		};

		collectionCustomer.Upsert(doeJohn);
		collectionCustomer.Upsert(doeJane);
		collectionCustomer.EnsureIndex(x => x.Id);
		
		collectionCustomer.Find(x => x.Name=="John Doe").Dump("Find John");
		collectionCustomer.Find(x => x.Name.Contains("Doe")).Dump("Find all Doe");
		collectionCustomer.Find(x => x.PaymentMethod==PaymentMethodType.Cash).Dump("Find all cash with enum does not work");
	}
}

// Define other methods and classes here
public enum PaymentMethodType
{
	None = 0,
	Cash = 1,
	CreditCard = 2
}
public class Customer 
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Description { get; set; }
	public PaymentMethodType PaymentMethod { get; set; }
}
```

**Expected behavior**
collection items with matching enum values should be returned

**Screenshots/Stacktrace**
![image](https://user-images.githubusercontent.com/809920/77364189-6b089500-6d2a-11ea-85cd-f99288454ccc.png)

**Comment by maxkatz6** [comment] 2020-03-24 07:44
Can you test it with latest master?
I think, it could be duplicate of https://github.com/mbdavid/LiteDB/issues/1548.

**Comment by lbnascimento** [comment] 2020-03-25 17:20
@hopson-2 I tested your example with master and it works. It was recently fixed and will be present in the next incremental release.

Also, a tip: there's no need to run `EnsureIndex` over the id field, since the index over the id is always created upon the first insertion and it can't be dropped.

**Closed by lbnascimento** 2020-03-25 17:20 UTC
Labels: bug

**Comment by hopson-2** [comment] 2020-03-25 18:12
Hello,
Thank you for the update and the tip.

--Glenn
