### ISSUE TITLE
Alias for types

### ISSUE THREAD

**Issue by alexandr2levin** [mbdavid/LiteDB#816] opened 2017-12-01 21:11 UTC
I want to have the ability to save type simply as `MessageUserItem`:

![image](https://user-images.githubusercontent.com/5736157/33503419-b29c8378-d6f4-11e7-8fcb-dd1db1b6e1cd.png)

It will simplify changes in data class's namespaces.
I want to implement it as `BsonTypeAliasAttribute`.
Are there any `BsonMapper`'s callbacks with I can give a try?

**Comment by mbdavid** [comment] 2017-12-05 11:55
Hi @Try4W, there is no callback for that `_type` is used when you insert a different object from collection type. LiteDB need full name to get instance after (using Type.GetType)

Write here:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Serialize.cs#L157

Read here:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Deserialize.cs#L159

**Comment by Try4W** [comment] 2017-12-11 10:05
Okay, I will try to implement my own BsonMapper, thanks.

**Comment by shorstok** [comment] 2018-01-17 20:52
To clarify, if I save entities and then do some refactoring - suppose, entity class moved from one namespace to another - then upon load attempt i'll get  `LiteException.InvalidTypedName` and there's currently nothing that can be done to get around it?

**Comment by mbdavid** [comment] 2018-01-18 09:33
@shorstok, if you change your class name or namespace you will must update your database data, updating `_type`. You can use generic `BsonDocument` to update this field or shell command. You can use `UserVersion` to track ths change:

```
if (db.Engine.UserVersion == 0) 
{
    db.Engine.Run("db.mycol.update _type="yourNewType, AssemblyName" where _type="...."); 
    db.Engine.UserVersion = 1;
}
```

**Comment by shorstok** [comment] 2018-01-18 09:37
wow, thanks for the quick answer.

**Comment by shorstok** [comment] 2018-01-18 10:33
I'm sorry but I cant get "db.mycol.update ..." working

Running query
`db.mycol.update _type="somespace2.SomeEntity, test"`
executes without errors but doesn't seem to modify any `_type` information in database, and adding where clause, for example:

`db.mycol.update _type="somespace2.SomeEntity, test" where _type="somespace2.Fx+SomeEntity, test"`

fails with `Unexpected token` exception no matter how i format it.

full code snippet:
```
var type = typeof(SomeEntity);

var oldTypeName = "somespace2.Fx+SomeEntity, test";
var newTypeName = type.FullName + ", " + type.GetTypeInfo().Assembly.GetName().Name;

var result  = db.Engine.Run($"db.mycol.update _type=\"{newTypeName}\" where _type=\"{oldTypeName}\""); 
```

But actual type names don't matter, it fails no matter what oldTypeName is

**Comment by mbdavid** [comment] 2018-01-21 18:16
Hi @shorstok, I just made an unit test example and don't get this error. Take a look here: https://github.com/mbdavid/LiteDB/commit/accc496a0e20e3ce8617c4f9e2d4087b4a43f53f#diff-e653114029a0296e1d143306e368408f

**Comment by shorstok** [comment] 2018-01-22 09:04
@mbdavid Strangely, your test executes fine and all asserts are OK, but `db.Engine.Run` still throws an LiteDB.LiteException 'Unexpected token'. I now see that I worked with 'Break on all CLR errors thrown' flag in exception settings and didnt even check whether it worked. I mean, this is not an expected behavior - no exception should be thrown upon valid query execution?...

Please run the test you provided with debugger on and set Studio to break on all CLR errors thrown in Debug -> Windows -> Exception Settings like this

![image](https://user-images.githubusercontent.com/17789212/35212718-bcfb11a8-ff63-11e7-9239-5b80c3cdd3f0.png)

to see if you get exception too.

And thank you for your responses :)

**Comment by mbdavid** [comment] 2018-01-22 23:08
Hi @shorstok, now I got it. That's because I implement a "too" simple parser in shell. Basically, when parsing command, first try `BsonExpression` value and , if got `LiteException` (Syntax Error) in this parse, try parse string as JSON value (string).

If you want avoid this, you must use an `foreach` statement and simple update one-by-one loop.

Is in my plans for v5 write a new `BsonExpression` parser and SQL-Like parser. So, in future, you will can write some like this:

```SQL
UPDATE mycol
   SET _type = REPLACE(_type, "OldAssembly", "NewAssembly")
 WHERE _type LIKE "%OldAssembbly"
```

**Comment by shorstok** [comment] 2018-01-23 08:48
Thank you for your answers, looking forward to v5 :)

**Comment by lbnascimento** [comment] 2020-02-28 13:39
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-28 13:39 UTC
