### ISSUE TITLE
Storing nested Dictionary<string, object>

### ISSUE THREAD

**Issue by superware** [mbdavid/LiteDB#489] opened 2017-02-15 13:17 UTC
Hello,

Please consider the following simple scenario:

```
var document = new Dictionary<string, object>()
{
	{ "Id", new Guid("f3378da5-9a0d-4857-9418-7991187aa58b") },
	{ "Name", "John Doe" },
	{ "Nested", new Dictionary<string, object>()
		{
			{ "Prop", "Value" }
		}
	}
};

using (var db = new LiteDatabase(@"temp.db"))
{
	var collection = db.GetCollection<Dictionary<string, object>>("MyCollection");

	collection.Insert(new BsonValue(document["Id"]), document);
}
```

Throws "Index was outside the bounds of the array." at BsonMapper.Serialize.cs `var itemType = type.GetGenericArguments()[1];` since `type` is a `System.Object`.

Any ideas?? Thank you in advance.

**Comment by mbdavid** [comment] 2017-02-15 23:28
Try convert your Dictionary<string, object> to BsonDocument (that inherits from `IDictionary<string, BsonValue>`), and than get collection like `db.GetCollection("MyCollection")`

**Comment by superware** [comment] 2017-02-17 06:37
Hello @mbdavid,

Thank you for your prompt response, can you please clarify? I'm just trying to insert a Dictionary<string, object> to the db. Convert how and why?

Thanks again.

**Comment by mbdavid** [comment] 2017-02-17 22:52
You cannot use Dictionary as base class in collection. If you want store schemeless structure using Dictionary, you need some like this:

```
public class Entity
{
    public int Id { get; set; }
    public Dictionary<string, object> Data { get; set; } = new Dictionary<string, object>();
}
```

Or, as I wrote, using BsonDocument, like:

```
var doc = new BsonDocument
{
    { "_id, 123 },
    { "key", value },
    { "embedded", new BsonDocument { .... }
}
```

**Comment by jlVidal** [comment] 2017-02-18 01:48
@mbdavid so just to clarify.. Currently LiteDb doesn't support save a multi-level dictionary? For example have a POCO class with a property type `Dictionary<string,object>`, and one of the pairs of that dictionary be another dictionary.

**Comment by mbdavid** [comment] 2017-02-18 11:54
Hi @jlVidal, now I get it, mading some tests here I understand the problem.

When you create Dictionary<string, object>, your value is "object" type and not specific type value. When this value is a simple/direct convert, like string or int, works fine. But if is another dictionary or array will get error.

I will evaluate this situation to see if is possible fix.

**Comment by mbdavid** [comment] 2017-02-18 12:32
Ok, I made some changes that works now. But are not 100% because to reproduce original dictionary, serialization must store `_type` in each nested object. I made as default, when deserialize and Bson Document to an "object", convert to "Dictionary<string, object>"

**Comment by mbdavid** [comment] 2017-02-18 12:33
```
            var mapper = new BsonMapper();

            // map dictionary to bsondocument
            var dict = new Dictionary<string, object>
            {
                ["_id"] = 1,
                ["MyString"] = "This is string",
                ["Nested"] = new Dictionary<string, object>()
                {
                    ["One"] = 1,
                    ["Two"] = 2,
                    ["Nested2"] = new Dictionary<string, object>()
                    {
                        ["Last"] = true
                    }
                },
                ["Array"] = new string[] { "one", "two" }
            };

            var doc = mapper.ToDocument(dict);
            var nobj = mapper.ToObject<Dictionary<string, object>>(doc);

            Assert.AreEqual(dict["_id"], nobj["_id"]);
            Assert.AreEqual(dict["MyString"], nobj["MyString"]);
            Assert.AreEqual(((Dictionary<string, object>)dict["Nested"])["One"], ((Dictionary<string, object>)nobj["Nested"])["One"]);
            Assert.AreEqual(((string[])dict["Array"])[0], ((object[])nobj["Array"])[0].ToString());
```

**Comment by jlVidal** [comment] 2017-02-20 18:52
@mbdavid  Thanks for the quick reply, I temporarily solved the issue doing:

         LiteDB.BsonMapper.Global.RegisterType<IDictionary<string, object>>(a =>
             {
                 return new BsonDocument(a.ToDictionary(b => b.Key, BsonValueFactory));
             }, b =>
             {
                 return new Dictionary<string, object>(((BsonDocument)b), StringComparer.OrdinalIgnoreCase);
             });
            return new object();
        }

        public BsonValue BsonValueFactory(KeyValuePair<string, object> a)
        {
            var innerDict = a.Value as IDictionary<string, object>;
            if (innerDict == null)
            {
                return new BsonValue(a.Value);
            }

            var serialized = new BsonDocument(innerDict.ToDictionary(b => b.Key, BsonValueFactory));
            return serialized;
        }

**Comment by lbnascimento** [comment] 2020-02-05 14:21
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-05 14:21 UTC
Labels: question
