### ISSUE TITLE
Exception Encountered

### ISSUE THREAD

**Issue by Lord-Haji** [mbdavid/LiteDB#593] opened 2017-05-04 06:01 UTC
``[01:23:30] (ERROR) Error: System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
at LiteDB.PageService.GetPage[T](UInt32 pageID, Boolean setDirty)
at LiteDB.TransactionService.Save()
at LiteDB.TransactionService.Complete(LiteTransaction trans)
at LiteDB.LiteTransaction.Commit()
at LiteDB.DbEngine.WriteTransaction[T](String colName, Boolean addIfNotExists, Func2 action) at LiteDB.LiteCollection1.Delete(Query query)
at PoGo.NecroBot.Logic.State.SessionStats.CleanOutExpiredStats() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 198
at PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\State\SessionStats.cs:line 84
at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.CheckSnipeConditions(ISession session) in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 298
at PoGo.NecroBot.Logic.Tasks.MSniperServiceTask.d__42.MoveNext() in C:\Users\VAPORSS\Documents\NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServiceTask.cs:line 786``
NecroBot-Private/NecroBot#1390

**Comment by Lord-Haji** [comment] 2017-05-04 06:02
@mbdavid #267 was a similar issue, which was closed not being resolved ?

**Comment by mbdavid** [comment] 2017-05-04 22:42
Hi @Lord-Haji, this bugs was found in another version but seams back in lasts version. It's occurs in some cases only when running in concurrency. It's on my plans made more tests to catch this.

**Comment by Splamy** [comment] 2017-05-08 15:06
Hey, I'm not sure if this is related but I have a very similar issue.
```
Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass61_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Insert(T document)
   at LiteDbRepro.Program.Main(String[] args) in E:\Desktop\Repro - Copy\LiteDbRepro\Program.cs:line 28
```
The file seems suddenly corrupted. I have no Idea how this happened since I got the files like that, but I will attach a small script which throws at the `Insert` in the current state.
I have tested this with the LiteDB.dll compiled from the master branch today.
[LiteDBRepro.zip](https://github.com/mbdavid/LiteDB/files/983906/LiteDBRepro.zip)

**Comment by mbdavid** [comment] 2017-05-08 22:46
Hi @Splamy, you file is corrupted by this bug. It's was happending in a unknow reason. Did you know how write a program that this problem occurs from an new datafile?

**Comment by Splamy** [comment] 2017-05-09 05:15
@mbdavid unfortunately not; this is the state I got the file from one of my users. I'll try around and see if I can somehow reproduce it again.

**Comment by EuanKirkhope** [comment] 2017-08-16 03:07
I have this problem too.

Exception thrown: 'System.InvalidCastException' in LiteDB
Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.ExtendPage'.   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.<GetSeqPages>d__7`1.MoveNext()
   at LiteDB.DataService.ReadExtendData(UInt32 extendPageID)
   at LiteDB.LiteEngine.<Find>d__52.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()

**Comment by mbdavid** [comment] 2017-08-16 15:56
Hi @EuanKirkhope, it´s a know bug in concurrency environment. I´m fixing this in current v3.5 dev branch... I'm releasing in beta version soon

**Comment by EuanKirkhope** [comment] 2017-08-29 11:52
David,  I'm still getting the same error with V4 of the lib, can you PM me an email, and I'll send you a DB, and test code.  I can't upload it publically.

**Comment by mbdavid** [comment] 2017-08-29 12:09
Hi @EuanKirkhope, please, fork my code and use LiteDb.Perf project to write your own example with this problem. An than I will get direct from your repo.

**Comment by lbnascimento** [comment] 2020-02-05 14:29
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-05 14:29 UTC
Labels: need review
