### ISSUE TITLE
[QUESTION] Best practices when using Xamarin.Forms

### ISSUE THREAD

**Issue by themronion** [mbdavid/LiteDB#1836] opened 2020-10-08 10:36 UTC
Hey guys. I would be grateful if someone can provide a small guide hot to use LiteDB v 5 in Xamarin.Forms - cause with the implementation i have now - i see that my db is not being disposed and the log file grows. All articles out there on the web are about v 4, so it would be cool to know how to add litedb v 5 to a xamarin app correctly. I can share my current implementation. Thanks in advance!

**Comment by lbnascimento** [comment] 2020-10-08 19:31
Duplicate of #1837, closed.

**Closed by lbnascimento** 2020-10-08 19:31 UTC
Labels: question

**Comment by PugTheMightyDog** [comment] 2022-07-08 21:57
Does the [LiteDB async ](https://github.com/mlockett42/litedb-async) nuget fix this behavior in Xamarin.Forms?
