### ISSUE TITLE
Error "Invalid format: Collection" when doing Upsert

### ISSUE THREAD

**Issue by pattisapu01** [mbdavid/LiteDB#554] opened 2017-03-29 02:57 UTC
I am trying to do an "Collection.Upsert" on the following POCO class. [There are other classes like this where upsert works fine!. Only this class fails]. The error is: **Error "Invalid format: Collection" when doing Upsert**
____________________
public class Order : BindableBase
    {
        public Order()
        {
            this.OrderItems = new List<string>();
        }
        public int Id { get; set; }
        [BsonRef("OrderMaster")]
        public OrderMaster OrderMaster { get; set; }
        public List<string> OrderItems { get; set; }
    }
_____________________
Stack trace:

> Invalid format: Collection
  at LiteDB.CollectionService.Add (System.String name) [0x0002b] in <b99fd1821def4ff9a5794b6636ed75ad>:0 
  at LiteDB.LiteEngine.GetCollectionPage (System.String name, System.Boolean addIfNotExits) [0x00035] in <b99fd1821def4ff9a5794b6636ed75ad>:0 
  at LiteDB.LiteEngine.Transaction[T] (System.String collection, System.Boolean addIfNotExists, System.Func`2[T,TResult] action) [0x00006] in <b99fd1821def4ff9a5794b6636ed75ad>:0 

> 

Thank you for the help..

**Comment by xied75** [comment] 2017-03-29 16:06
When you paste code block, you can use three back tick to quote it.

Are your other working collections all derived from BindableBase?

**Comment by mbdavid** [comment] 2017-03-30 09:49
What collection name are you using when you call `GetCollection`?

**Comment by ptrpt** [comment] 2017-05-04 16:44
I add a similar problem. I was using a GUID string to name collections. Then I realised that Collection naming can not include '-' character. I then replaced the '-' for a '_'. But it didn't make it for me. Still had the problem. Finally I decided to shorten the name (it now has 7 characters) and, hurray, it is working.

**Comment by ftamminga** [comment] 2017-06-23 13:26
I have the same problem and I think I know where the problem lies.
If a collection name exceeds 30 positions, it fails!

Could you please increase the limit of the name, or at least generate some kind of error...

**Comment by alexandervantrijffel** [comment] 2017-07-03 12:02
The 30 characters limitation for a collection name is very restrictive. This does not allow me to store an instance of a class with a name like TransformationPlannerSagaStateMachine. This fails:

```
var collection = db.GetCollection<TSaga>();
collection.Insert(context.Saga);
```

Can the name limit be increased?

**Comment by MrSmoke** [comment] 2017-07-27 04:30
I think it should be at minimum 32 characters, that way we can use guids (without -) and/or MD5 the content as the collection name

**Comment by leek9** [comment] 2017-07-27 18:21
Length limitation of 30 verified. So basically this code
`db.GetCollection<T>("AAAA5AAA10AAA15AAA20AAA25AAA30A").Insert(data);`
will get you this error:
>    at LiteDB.CollectionService.Add(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)
   at LiteDB.LiteCollection`1.Insert(IEnumerable`1 docs)

**Comment by mbdavid** [comment] 2017-08-03 19:25
Hi @MrSmoke and @leek9 changed in dev branch a14b8e6 - 60 char max length. Will be available in next major version 3.5

**Comment by corelgott** [comment] 2017-11-09 07:38
It still seems to be limites to 30 charaters in version 4.0
`LiteDB/LiteDB/Engine/Structures/CollectionIndex.cs`
`public static Regex IndexPattern = new Regex(@"^[\w](\.?[\w\$][\w-]*){0,29}$", RegexOptions.Compiled);`

Am I missing something?

**Comment by mbdavid** [comment] 2017-11-10 12:32
Hi @corelgott, humm... really strange. I think that I change in twice and, when git request a merge (in vim) i just do :wq 😄 I will back to 60 in both cases

**Comment by mbdavid** [comment] 2017-12-11 12:38
Hi @vanufryiuk, soon... maybe this week :) I'm will release v4.0.1 before v4.1 that I'm working in another branch.

**Comment by syaifuri** [comment] 2017-12-19 12:48
Shit, almost 2 days do debugging the code, finally find the cause of "exception: invalid format" is due to character over than 30.
i use version runtime : v4.0.30319

**Comment by mbdavid** [comment] 2017-12-19 12:57
Upgrade do 4.1, it´s fixed now in 60 chars (at limit of 3000 for all collections names)

**Comment by RenniePet** [comment] 2018-04-07 00:15
It would be nice with more explicit error messages than just "Invalid format". For example "Name too long" and "Invalid character in name" and ...

**Comment by lbnascimento** [comment] 2020-02-05 14:27
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-05 14:27 UTC
Labels: question
