### ISSUE TITLE
New version - v3.5 beta

### ISSUE THREAD

**Issue by mbdavid** [mbdavid/LiteDB#682] opened 2017-08-07 00:21 UTC
Hi guys, after some weeks of hard work I got a beta version of LiteDB v3.5. I'm not releasing on nuget yet because I will do more tests on changes. This new version has some break changes (all source are in `dev` branch).

The main goal of this version is fix concurrency problems that LiteDB has in v2.x and v3.x. In order to do this I had to change some features.

## Changes
- Remove transactions **(break-api)**
- Remove physical journal file (store journal pages after file ends)
- Remove auto-id register function for custom type **(break-api)**
- Remove index definitions on mapper (fluent/attribute) **(mark as obsolete)**
- Remove auto create index on query execution. If the index is not found do full scan search (use `EnsureIndex` on initialize database is better solution)
- NET45 compiles as NET35
- Update to VS2017

## Features
- Add auto-id in engine level with pre-defined common types
- Add collection sequence (`ulong`) to use in engine level auto-id
- Implement FilterDocument option in all query implementations (full scan document)
- In `Query.And` use only one index side with full scan on other
- Print query execution plan in Query.ToString() `Seek([Age] > 10) and Scan([Name] startsWith "John")`
- Convert `Query.And` to `Query.Between` when possible
- Add support to `Query.Between` open/close interval
- `QueryLinq` for non resolved linq expression on visitor `col.Find(x => x.Id < 10 && x.Name.Length > 10)` will works using `Id` index and linq expression execution of `Name.Length > 10`

Also, I added a new LiteDB.Perf to test concurrency problems.

If you want contribute, fork my `dev` branch and change LiteDB.Perf to try get concurrency this error: **Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'**. Tell me here in this issue that I will investigate.

Let's turn LiteDB into a rock solid database 😄 🎉 

Here, some issues that refer this concurrency problem: #641 #650 #619 #639 #592

Thanks!

**Comment by lidanger** [comment] 2017-08-07 09:32
It seems there is still problems in multithread case.

System.NullReferenceException
   在 LiteDB.LiteEngine..ctor(LiteDB.IDiskService, System.String, System.Nullable`1<System.TimeSpan>, Int32, LiteDB.Logger)
   在 LiteDB.LiteEngine..ctor(System.String, Boolean)
   在 LiteDB.Perf.Program.ExecuteTest(System.String, System.Action)
   在 LiteDB.Perf.Program+<>c.<Main>b__4_0()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Threading.ThreadHelper.ThreadStart()

System.IO.IOException
   在 System.IO.__Error.WinIOError(Int32, System.String)
   在 System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   在 System.IO.FileStream.Write(Byte[], Int32, Int32)
   在 LiteDB.LiteEngine.CreateDatabase(System.IO.Stream, System.String)
   在 LiteDB.FileDiskService.Initialize(LiteDB.Logger, System.String)
   在 LiteDB.LiteEngine..ctor(LiteDB.IDiskService, System.String, System.Nullable`1<System.TimeSpan>, Int32, LiteDB.Logger)
   在 LiteDB.LiteEngine..ctor(System.String, Boolean)
   在 Test.Program.ExecuteTest(System.String, System.Action)
   在 Test.Program.testThread()
   在 System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Threading.ThreadHelper.ThreadStart()

How about add Monitor.Enter in LiteDatabase constructor and Dispose function to avoid the multithread problem?Or add Mutex in LiteDatabase constructor to avoid MultiProcess problem?

**Comment by mbdavid** [comment] 2017-08-07 11:13
Hi @lidanger what OS are you using and this D:\ is local disk? Because this error are in File.Delete on Program.cs (Not in litedb)

**Comment by lidanger** [comment] 2017-08-07 13:32
D:is a ssd.
OS:win10 15063
@mbdavid

**Comment by mbdavid** [comment] 2017-08-07 13:45
I'm using win10 too in a local disk (ssd too). Your error message seams file are closed when File.Delete are called. The program run first test (are 2 tests, one as process and one for thread)? Did you do any change on LiteDB.Perf?

**Comment by lidanger** [comment] 2017-08-07 13:49
Yes.I modify some,because I feel the time of the running is tool short.

**Comment by mbdavid** [comment] 2017-08-07 13:50
is this source on you github? how can I test?

**Comment by lidanger** [comment] 2017-08-07 13:53
@mbdavid  Yes,it is.It's on my github.

**Comment by mbdavid** [comment] 2017-08-07 13:57
I didn't found in you github (only found fork from master). Send me your source link to check

**Comment by lidanger** [comment] 2017-08-07 14:01
class Program
    {
        static string filename = "file_demo.db";
        static Logger log = new Logger(Logger.NONE, (s) => Console.WriteLine("#" + Thread.CurrentThread.ManagedThreadId.ToString("00") + " " + s));
        static int TASKS = 300;
        static Random rand = new Random(DateTime.Now.Millisecond);

        static void Main(string[] args)
        {
            // log.Level = Logger.DISK | Logger.LOCK;

            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

            Thread thd = null;
            for (int i = 0; i < 10; i++)
            {
                thd = new Thread(() =>
                {
                    ExecuteTest("Process", TestProcess);
                    ExecuteTest("Thread", TestThread);

                    Thread.Sleep((int)(rand.NextDouble() * 10 * 1000));
                });
                thd.IsBackground = true;
                thd.Start();
            }

            Console.WriteLine("End");
            Console.ReadKey();
        }

        private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            File.AppendAllText("error.log", string.Format("{0}", e.ExceptionObject));
        }

        static LiteEngine InitDB()
        {
            var disk = new FileDiskService(filename, true);
            return new LiteEngine(disk, null, null, 5000, log);
        }

        static void ExecuteTest(string name, Action test)
        {
            Console.WriteLine("{0} (N = {1})", name, TASKS);

            // delete datafile before starts
            //File.Delete(filename);

            // create empty database and collection with index in name
            using (var db = new LiteEngine(filename))
            {
                db.EnsureIndex("collection", "name");
            }

            var s = new Stopwatch();
            s.Start();

            // execute test
            test();

            s.Stop();

            Console.WriteLine("Time Elapsed (ms): " + s.ElapsedMilliseconds);
            Console.WriteLine();

            // assert if database are ok
            Assert();
        }

        static void RunTask(LiteEngine db)
        {
            for(var i = 0; i < 10; i++)
            {
                var doc = new BsonDocument() { ["name"] = "testing - " + Guid.NewGuid() };

                db.Insert("collection", doc, BsonType.Int32);

                doc["name"] = "changed name - " + Guid.NewGuid();

                db.Update("collection", doc);
            }

            db.Find("collection", Query.LTE("_id", 100)).ToArray();
        }

        static void Assert()
        {
            // checks if are ok
            using (var db = new LiteEngine(filename))
            {
                db.FindAll("collection").ToArray();
            }
        }

        #region Process/Thread Testing

        static void TestProcess()
        {
            var tasks = new List<Task>();

            for (var i = 0; i < TASKS; i++)
            {
                var t = Task.Factory.StartNew(() =>
                {
                    using (var db = InitDB())
                    {
                        RunTask(db);
                    }
                });

                tasks.Add(t);
            }

            Task.WaitAll(tasks.ToArray());
        }

        static void TestThread()
        {
            var tasks = new List<Task>();

            using (var db = InitDB())
            {
                for (var i = 0; i < TASKS; i++)
                {
                    var t = Task.Factory.StartNew(() =>
                    {
                        RunTask(db);
                    });

                    tasks.Add(t);
                }

                Task.WaitAll(tasks.ToArray());
            }

        }

        #endregion  
    }

@mbdavid I have commented File.Delete..Sorry, it's a mistake.

**Comment by lidanger** [comment] 2017-08-07 14:08
thd = new Thread(() =>
                {
                    DateTime dt = DateTime.Now;
                    while (DateTime.Now < dt.AddHours(2))
                    {
                        ExecuteTest("Process", TestProcess);
                        ExecuteTest("Thread", TestThread);

                        Thread.Sleep((int)(rand.NextDouble() * 10 * 1000));
                    }
                });

**Comment by mbdavid** [comment] 2017-08-07 14:10
Ok, i'm running your test now... without File.Delete are working, but will take some time, because are 10 threads with 300 tasks each. I dont know if there is no timeout exception because are many waiting process.

**Comment by lidanger** [comment] 2017-08-07 14:14
I think execute tasks once is tool short to test,so..Maybe not need that much threads.

**Comment by mbdavid** [comment] 2017-08-07 14:18
Let´s put LiteDB on a super stress test :) I think a web api (get/post/put/delete) with a JMeter stress tool could be nice too to test more real scenarios.

**Comment by lidanger** [comment] 2017-08-07 14:19
Yes,it should be nice.

**Comment by mbdavid** [comment] 2017-08-07 14:37
Done, 10 threads works fine - produces 18mb file_demo.db - 60.000 records. Tell me if you have any trouble in your 2 hours test.

**Comment by mbdavid** [comment] 2017-08-07 19:44
Ok, created a CRUD webapi example and run over stress tool. All operations (Find, Insert, Update, Delete) and until now no problems. Tested over multi process and multi thread.

https://github.com/mbdavid/LiteDB.WebApi

Multi thread are 5 times faster than multi process (avoid open/close file + cache)

**Comment by martinrotter** [comment] 2017-08-08 04:24
Will data file from 3.0 work for 3.5? Any migration will be needed?

**Comment by lidanger** [comment] 2017-08-08 06:13
Hi,@mbdavid .Sorry,I can't complete the test because there is too many timeout.I have reduced it to 10 tasks, but no help.

some error:
1.If there is no file, it report nullexception:

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
   在 LiteDB.LiteEngine..ctor(String filename, Boolean journal)
   在 LiteDB.Perf.Program.ExecuteTest(String name, Action test) 位置 D:\LiteDB\LiteDB.Perf\Program.cs:行号 66
   在 LiteDB.Perf.Program.<>c.<Main>b__4_0() 位置 D:\LiteDB\LiteDB.Perf\Program.cs:行号 33
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

2.convert emptypage to datapage error.test for 15 minutes.

System.InvalidCastException
   在 LiteDB.PageService.GetPage[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](UInt32)
   在 LiteDB.DataService.GetBlock(LiteDB.PageAddress)
   在 LiteDB.DataService.Read(LiteDB.PageAddress)
   在 LiteDB.QueryContext+<GetDocuments>d__13.MoveNext()
   在 System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertRange(Int32, System.Collections.Generic.IEnumerable`1<System.__Canon>)
   在 LiteDB.LiteEngine+<Find>d__9.MoveNext()
   在 System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   在 System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   在 LiteDB.Perf.Program.Assert()
   在 LiteDB.Perf.Program.ExecuteTest(System.String, System.Action)
   在 LiteDB.Perf.Program+<>c.<Main>b__4_0()
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by mbdavid** [comment] 2017-08-08 09:14
@martinrotter no changes on datafile structure. It's same file, no migrations.

@lidanger about timeout, it's ok if you get too much concurrency. You can increase this time.

But, about this second error, it's the lock problem again. But know I have where it's happening. It's on "get all data". This new version store in cache query results before returns. Default is 100 document in cache. After this, query release read lock, returns this 100 documents, and lock again to get more 100 documents. In this mean time, you are deleting data. For now, if you increase this number to much more you will not get this problem. I will review this implementation to try avoid this.

**Comment by lidanger** [comment] 2017-08-08 09:30
I think I forgot another error.
Sometimes, when the program report exception and exit and the data file is not deleted, the program is restarted again, but with only one cycle, it blocks.
The real problem is the data file can not be deleted later and the program can not be closed even using taskmanager.TaskManager report an error: access refused.The only way to release the lock is rebooting the OS.
@mbdavid

**Comment by lidanger** [comment] 2017-08-09 04:51
With log4net for exception logging, I tested it for 2 hours just now.No error come out, except few timeout.
Environment:Windows Server 2012 R2 DataCenter on Alibaba Cloud.
Thread:10
Tasks:10
The size of the file file_demo.db is 73992KB.

Code In Here:[https://github.com/lidanger/LiteDB/blob/dev/LiteDB.Perf/Program.cs](https://github.com/lidanger/LiteDB/blob/dev/LiteDB.Perf/Program.cs)

**Comment by mbdavid** [comment] 2017-08-09 17:19
Thats nice @lidanger. I update query implementation to alwyas re-query after each lock/unlock. It´s not faster solution, but it´s safest option to not get this kind of error.

I'm still doing more load/stress test. Please, tell me if you got some concurrency error

**Comment by lidanger** [comment] 2017-08-10 02:03
Today, I use hyper-v to simulate power failure, then the exception come out again.

environment:
Windows XP Professional SP3
.net frameword 4.0 full

threads:10

tasks:10

call stack:
[2017-08-10 09:29:39,817] [DEBUG] Main - RunTask exception:System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass18_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.Perf.Program.RunTask(LiteEngine db) in E:\LiteDB\LiteDB.Perf\Program.cs:line 103

@mbdavid

**Comment by mbdavid** [comment] 2017-08-10 11:41
Hi @lidanger, I dont know if WriteThrough will resolve this.

Question: when you back after failure process, you start all threads again? Could by some concurrency problem in Restore operation. I will do double-check in Restore process.

**Comment by lidanger** [comment] 2017-08-10 14:15
This can be easily reproduced with a virtual machine.
I use hyper-v. When the program runs for some time, then I power down the machine and restart the virtual machine and the program later.
I think other virtual machine, such as VirtualBox, will take same effect.
@mbdavid Adding WriteThrough can be a option that I have tested, but it's a slow solution.

**Comment by lbnascimento** [comment] 2020-02-05 17:41
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-05 17:41 UTC
Labels: need review
