### ISSUE TITLE
Variable of type referenced from scope '', but it is not defined exception

### ISSUE THREAD

**Issue by MrSmoke** [mbdavid/LiteDB#637] opened 2017-06-28 01:31 UTC
If I call `Delete(Expression<Func<T, bool>> predicate)` in this order:

```c#
Guid id;
.Delete(x => id.Equals(x.TestId));
```

instead of 

```c#
Guid id;
.Delete(x => x.TestId.Equals(id));
```

I get the following exception:

```
System.InvalidOperationException: 'variable 'x' of type 'Test.Item' referenced from scope '', but it is not defined'
```

**Comment by mbdavid** [comment] 2017-07-01 23:46
If @MrSmoke, yes. It's not a bug, it's a feature :) It's happening because LINQ compiler it's a very complicated to implement all Visitors to check all tree expressions. In LiteDB I implement only simple operation, always using field in left and value in right.

**Comment by PGardockiDotNet** [comment] 2018-06-27 14:21
MrSmoke, I am currently working this bug, and only have a partial answer.  In the first example, for some reason, x is actually compiled as two different variables, both with the name of x.  How to fix this I am still working on.  There are references to a fix in .NET 4.0+ using possibly ExpressionRewriter , but I haven't worked it out yet.  There is a page covering this is in StackOverflow.  https://stackoverflow.com/questions/30556911/variable-of-type-referenced-from-scope-but-it-is-not-defined

**Comment by lbnascimento** [comment] 2020-02-28 13:48
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-28 13:48 UTC
