### ISSUE TITLE
LiteDatabase.Checkpoint() method causes a deadlock

### ISSUE THREAD

**Issue by sqlite-me** [mbdavid/LiteDB#1511] opened 2020-02-26 07:50 UTC
**Version**
5.0.3.0/Windows 7/.NET framework 4.5

**Describe the bug**
Affter called ILiteCollection<T>.Insert(),calling LiteDatabase.Checkpoint().LiteDatabase.Checkpoint() method causes a deadlock.

**Code to Reproduce**
            var t = 0;
            while (true)
            {
                if (testDb == null) testDb = new LiteDatabase("datas\\test.ldb");
                for (var i = 0; i < 5; i++)
                    testDb.GetCollection<TestData>().Insert(new TestData { Name = "name" + (t++) });
                
                testDb.Checkpoint();
            }

**Screenshots/Stacktrace**
![image](https://user-images.githubusercontent.com/23652113/75323260-7d202080-58af-11ea-9f17-9b9db21d82f7.png)

**Comment by lbnascimento** [comment] 2020-02-27 14:13
@sqlite-me I could not reproduce the issue with the code you provided. Could you provide us more info or perhaps another piece of code that could be used to reproduce the issue?

**Comment by sqlite-me** [comment] 2020-02-28 08:37
This is a finished example. I reproduced the problem when I tested it.Let the program run longer, with a certain probability.
**Code**
    class TestData
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var testDb = new LiteDatabase("test.ldb");
            var count = 0;
            while (true)
            {
                for (var i = 0; i < 5; i++)
                {
                    testDb.GetCollection<TestData>().Insert(new TestData { Name = "name" + (count++) });
                }
                testDb.Checkpoint();

                Console.WriteLine(count);
            }

        }
    }

**Comment by sqlite-me** [comment] 2020-02-28 09:10
in class  _"LiteDB.Engine.DiskWriterQueue"_
When method **_Wait()_** executes to **_waiter.Set();_**, and method **_CreateThread()_** executes to **_while(_running)_**.
Next,method **_Wait()_** executes to _**_writing.Wait();_**, and method **_CreateThread()_** executes to **_waiter.Wait()_**, both threads may  wait forever.

**Comment by mbdavid** [comment] 2020-03-03 13:56
Hi @sqlite-me, I remove this waits and use a simple task re-creating. Will be avaiable in next minor release

**Comment by zandam-xrn** [comment] 2020-08-05 12:04
Hi @mbdavid has this bug already been released?

**Comment by lbnascimento** [comment] 2020-08-05 14:12
@zandam-xrn Yes, this has been fixed. We forgot to close the issue somehow.

**Closed by lbnascimento** 2020-08-05 14:12 UTC
Labels: bug, fixed
