### ISSUE TITLE
How to query and return specific embedded documents?

### ISSUE THREAD

**Issue by abhishekginani-tm** [mbdavid/LiteDB#850] opened 2017-12-22 09:39 UTC
I have BSON docs like below:
```
{ 
"user" :"1",
"quescode":[
                    
                     { "Qcode":" q101" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q102" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q104" , "anscode":[1,2,3,4,5,6] }
                     .
                     .
                     .
                     { "Qcode":" qN" , "anscode":[1..10] }
                    ]
},
{ 
"user" :"2",
"quescode":[
                    
                     { "Qcode":" q101" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q102" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q104" , "anscode":[1,2,3,4,5,6] }
                     .
                     .
                     .
                     { "Qcode":" qN" , "anscode":[1..10] }
                    ]
},
.
.
.
.
.
{ 
"user" :"upto 1 Million",
"quescode":[
                    
                     { "Qcode":" q101" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q102" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q103" , "anscode":[1,2,3,4,5,6] }
                     { "Qcode":" q104" , "anscode":[1,2,3,4,5,6] }
                     .
                     .
                     .
                     { "Qcode":" qN" , "anscode":[1..10] }
                    ]
}
```
I want to get all the users containing specific **QCode**(ex: q104).

I have tried below code  to query:

` var data = col.Find(LiteDB.Query.EQ("quescode[*].Qcode", "q104"`));

This returns complete documents of the users with all the Qcodes. Is there any  way to get only specific Qcode from the embedded document with user detail from parent doc like
```
{
{ 
"user" :"1",
"quescode":[ { "Qcode":" q101" , "anscode":[1,2,3,4,5,6] }]
},

{ 
"user" :"2",
"quescode":[{ "Qcode":" q101" , "anscode":[1,2,3,4,5,6] } ]
}

}
```
Any clue how to query to get above results?

**Comment by abhishekginani-tm** [comment] 2017-12-22 10:29
@mbdavid: Please help on this

**Comment by mbdavid** [comment] 2017-12-22 12:55
In v4 you can write expression and transform output. Its use shell command:

```
db.yourcollection.select
{
    user: $.user,
    quescode: ARRAY($.quescode[@.Qcode = 104])
} 
where $.quescode[*].Qcode = 104
```

But for better performance, you can first create an index in your QCode, like this:

```
col.EnsureIndex("idx_qcode", "$.quescode[*].Qcode")
```

and than change here:

```
db.yourcollection.select
{
    user: $.user,
    quescode: ARRAY($.quescode[@.Qcode = 104])
} 
where idx_qcode = 104
```

To call this shell commands in you aplication, use:

`db.Engine.Run(string shell_command)`

**Comment by abhishekginani-tm** [comment] 2017-12-22 13:36
Getting error  -  **unexpected token**

**C# Code:** 

`var data2=_engine.Run("db.data.select {user: $.user, quescode: ARRAY($.quescode[@.Qcode = q104])} where idx_qcode = q104");`

**Comment by mbdavid** [comment] 2017-12-22 15:17
Was missing single quotes in expression and double quotes in value

![image](https://user-images.githubusercontent.com/1137197/34302951-673c97ca-e71a-11e7-81d7-5de96fe36769.png)

**Comment by abhishekginani-tm** [comment] 2017-12-22 15:52
Thanks, Works perfectly. But this is taking too much time(about 2mins) while querying. Any suggestion to improve the performance?

**Comment by mbdavid** [comment] 2017-12-22 16:04
are you using index like in my example? There is other filter that you are using?

**Comment by abhishekginani-tm** [comment] 2017-12-22 16:18
Yes, I m using indexes while querying.
No other filters in the query. Should  I change storage format of JSON docs? Please suggest.

**Comment by mbdavid** [comment] 2017-12-22 16:24
You model are ok if your "quescode" are quite small (like 10 or 100 rows).  But how much documents are returning? `Run` method returns as `IList`, so if you returning too much documents, all of them are in memory. If you need paging, append ` skip 0 limit 100` in your shell command

**Comment by abhishekginani-tm** [comment] 2017-12-22 16:29
Total 3200 quescodes are there. 10000 docs returned from the query. I ran the query on the command line.

**Comment by abhishekginani-tm** [comment] 2017-12-22 16:39
Up to  1 million documents are possible in the database

**Comment by mbdavid** [comment] 2017-12-22 16:53
In this case you have a quite long list to return/print on screen. This shell tool are not optimized for large print volume.
There is no problem to have 100.000 or 1 million documents, the problem is if you want all of them in single query return.
Try use command: `timer` to check how long you get 100 documents. (using `limit`)

**Comment by abhishekginani-tm** [comment] 2017-12-22 17:25
Is group by possible in LiteDB?

**Comment by abhishekginani-tm** [comment] 2017-12-22 17:34
Below code takes very less time as compare to the command 

`var data = col.Find(LiteDB.Query.EQ("quescode[*].Qcode", "q3001"));`

**Comment by abhishekginani-tm** [comment] 2017-12-22 17:45
100 docs takes 2508 miliseconds

**Comment by mbdavid** [comment] 2017-12-22 17:54
there is no group by yet.... but, as an embedded database, you can use `GroupBy` from Linq to object.

That's quite strange full scan run faster than index search. To compute all time used you need apply `ToList()` to convert your `IEnumerable` into a list.

**Comment by abhishekginani-tm** [comment] 2017-12-25 06:31
Yes, now it takes too long after applying`.ToList()`. But the problem is after using indexes it takes 2mins to return the data. Can you please help me to resolve this performance problem by changing data storage model or any clue you have which can improve?

**Comment by mbdavid** [comment] 2017-12-25 12:37
Can you attach your database or paste your script to create mock this data?

**Comment by abhishekginani-tm** [comment] 2017-12-25 16:05
Adding code to generate the data. 
This may take long to generate data. I don't know how this can be improved for fast loading as it takes 1-2 Seconds to push single Document. Below are the two main issues am facing with the DB 

1: Fast loading of data into LiteDB with indexes.
2: Querying data based on the `Qcode` and `anscodes `. 

C# Code:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LiteDB;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            LiteDatabase db = new LiteDatabase("testdata.db");
            var coll = db.GetCollection<users>("data");
            List<int> anscodes = new List<int>();
            anscodes = Enumerable.Range(1, 10).ToList();

            List<Questions> lstqs = new List<Questions>();
            for (int i = 1; i <= 300000; i++)
            {
                Console.WriteLine("start" + DateTime.Now);
                users usr = new users();
                for (int j = 1; j <= 3200; j++)
                {

                    Questions qs = new Questions();
                    qs.Qcode = "q" + j.ToString();
                    qs.anscode = anscodes;
                    lstqs.Add(qs);

                }
                usr.quescode = lstqs;
                usr.user = i;
                coll.Insert(usr);
                coll.EnsureIndex("idx_qcode", "$.quescode[*].Qcode");
                lstqs.Clear();
                Console.WriteLine("end" + DateTime.Now);
            }
        }

        public class users
        {

            [BsonId]
            public int ID { get; set; }
            public int user { get; set; }
            public List<Questions> quescode { get; set; }
        }

        public class Questions
        {
            public string Qcode { get; set; }
            public List<int> anscode { get; set; }
        }
    }

}
```

**Comment by abhishekginani-tm** [comment] 2017-12-27 05:44
@mbdavid Did you get the chance to look at this?

**Comment by mbdavid** [comment] 2017-12-27 11:02
Hi @abhishekginani-tm, each document are too large (each user has 3200 array items with more 10 items in each array). Each user consume 350kb of data (just to serialize). This will result 97 GB of data, just to store (without any index).

You can normalize you model putting userID into Question class, like this:

    public class Questions
    {
        public int ID { get; set; }
        public int user { get; set; }
        public string Qcode { get; set; }
        public List<int> anscode { get; set; }
    }

But, in your simulation, 300.000 users with 3200 question each, you will have about 960 millions documents. You probably need a server database for that. If you want keep with local database, you will need an strategy to split this data in several datafiles, using some rule do redirect users (like first letter name).

**Comment by lbnascimento** [comment] 2020-02-06 17:31
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Closed by lbnascimento** 2020-02-06 17:31 UTC
