### ISSUE TITLE
[QUESTION] Can LiteCollection be used in Concurrency?

### ISSUE THREAD

**Issue by sanju-singh** [mbdavid/LiteDB#1631] opened 2020-04-14 08:53 UTC
**Code to Reproduce**
```
protected async virtual Task<IEnumerable<T>> ReadAllItems<T>(LiteCollection<T> collection)
{
    return await Task.Run(() =>
    {
          return collection.FindAll().ToList();
     });
}
```

I am getting the collection objection once and passing it to the above method. calling above method multiple times causing the error SIGSEGV.

Wanted to confirm if we support LiteCollection in concurrency?

**Comment by lbnascimento** [comment] 2020-04-14 14:23
@sanju-singh I'm going to close this, since it is a duplicate of #1627. Let's keep all future discussions there.

**Closed by lbnascimento** 2020-04-14 14:23 UTC
Labels: question
