### ISSUE TITLE
[BUG]Maximum number of transactions reached

### ISSUE THREAD

**Issue by 5d2** [mbdavid/LiteDB#1772] opened 2020-08-02 06:27 UTC
V5.08

Exception **Maximum number of transactions reached** 

**CODE**

`var col = _db.GetCollection<T>(typeof(T).Name);
                result = col.Find(bse).ToList();`
`var col = _db.GetCollection<T>(typeof(T).Name);
                t = col.FindById(new ObjectId(Id)) :`

**Comment by lbnascimento** [comment] 2020-08-03 14:33
@5d2 I could not reproduce the issue. What .NET implementation are you using? Could you provide a complete sample code that I could use to reproduce the issue?

**Comment by mookid8000** [comment] 2020-09-01 19:01
In case this could help, I can report having experienced the following: Following some fairly heavy load, the following error error occurred:
```
System.ArgumentException: An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at LiteDB.Engine.BasePage.Defrag()
   at LiteDB.Engine.BasePage.InternalInsert(UInt16 bytesLength, Byte& index)
   at LiteDB.Engine.BasePage.Update(Byte index, UInt16 bytesLength)
   at LiteDB.Engine.DataPage.UpdateBlock(DataBlock currentBlock, Int32 bytesLength)
   at LiteDB.Engine.DataService.<>c__DisplayClass4_0.<<Update>g__source|0>d.MoveNext()
   at LiteDB.Engine.BufferWriter..ctor(IEnumerable`1 source)
   at LiteDB.Engine.DataService.Update(CollectionPage col, PageAddress blockAddress, BsonDocument doc)
   at LiteDB.Engine.LiteEngine.UpdateDocument(Snapshot snapshot, CollectionPage col, BsonDocument doc, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass26_0.<Update>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at FleetManager.Model.Tech.LiteDb.LiteDbProjection`1.<Flush>d__16.MoveNext() in C:\projects-rebusfm\fm7-server\FleetManager.Model.Tech\LiteDb\LiteDbProjection.cs:line 159
```
when calling `ILiteCollection<T>.Update(IEnumerable<T> entities)`.

After having thrown that error for a while, LiteDB started giving off error messages like
```
LiteDB.LiteException: Invalid Data on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 1959. ShareCounter: -1. 

System.InvalidCastException: Unable to cast object of type 'LiteDB.Engine.HeaderPage' to type 'LiteDB.Engine.DataPage'.

LiteDB.LiteException: Invalid Data on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 5674. ShareCounter: -1. 

LiteDB.LiteException: Invalid Collection on 1365001555. Full zero: False. Page Type: 65. Prev/Next: 1768835387/1818323316. UniqueID: 7045. ShareCounter: 9. 

System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
```
until finally settling on 
```
LiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FleetManager.Model.Tech.LiteDb.LiteDbProjection`1.<WarmUp>d__14.MoveNext() in C:\projects-rebusfm\fm7-server\FleetManager.Model.Tech\LiteDb\LiteDbProjection.cs:line 93
```
until the process was stopped.

**Comment by KC7465128305** [comment] 2020-09-19 22:01
I have the same problem and I am using v5.0.9 so the bug hasn't been fixed.  This is what triggers this exception:

((LiteCollection<POCOFrm>)MyDB.NoSqlDB.GetCollection<POCOFrm>("Frm")).FindOne(p => p.Id == ID);

**Comment by KC7465128305** [comment] 2020-09-19 23:10
Got another "Maximum number of transactions reached" bug when my program run the following statement:

LiteDB.IBsonDataReader reader = MyDB.NoSqlDB.Execute($"SELECT _id FROM Ctl ORDER BY _id DESC LIMIT 1");

**Comment by frankneumann** [comment] 2020-12-26 09:33
I encountered the same exception, which was caused by the heavy use of threads within _Parallel.ForEach_. Unfortunately, the _TransactionService_ for a closed thread will not be removed from the __transactions_ dictionary within the _TransactionMonitor_.
Here a finalizer for the _TransactionService_ has to be added, which takes care of removing the transaction from the  __transactions_ dictionary. I will provide a fix for this.

**Comment by mbdavid** [comment] 2021-01-22 14:57
Hi @frankneumann , thanks for solving this. Can you submit a Pull Request about this bugfix?

**Comment by frankneumann** [comment] 2021-01-22 15:01
It is here:
https://github.com/mbdavid/LiteDB/pull/1906

**Comment by balverio** [comment] 2021-02-05 16:31
@mbdavid @frankneumann My company needs this fix, do you know when it will be released and what version?

**Comment by lbnascimento** [comment] 2021-07-21 18:45
It is fixed in the latest release.

**Closed by lbnascimento** 2021-07-21 18:45 UTC
Labels: bug
