### ISSUE TITLE
[BUG] Empty value in indexed field throws exception

### ISSUE THREAD

**Issue by utech626** [mbdavid/LiteDB#1597] opened 2020-03-28 20:17 UTC
**Version**
5.05
Framework Version 4.8

**Describe the bug**
When inserting a record with a Empty String in a indexed field and exception is thrown.

**Code to Reproduce**
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using LiteDB;

namespace LiteDBBug
{
	public class MyRecord
	{
		[BsonId]
		public int Id { get; set; }
		public String Field11 { get; set; }
		public String Field22 { get; set; }
		public String Field33 { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			using (LiteDatabase _db = new LiteDatabase(@"MyData.db"))
			{
				var _col = _db.GetCollection<MyRecord>("records");

				_col.EnsureIndex(x => x.Field22, unique: false);

				var _rec1 = new MyRecord
				{
					Field11 = "value1",
					Field22 = "value2",
					Field33 = "value3"
				};
				//
				//	**Success** 
				//
				_col.Insert(_rec1);

				var _rec2 = new MyRecord
				{
					Field11 = "value1",
					Field22 = "",
					Field33 = "value3"
				};
				//
				//	**null reference exception**
				//
				_col.Insert(_rec2);
			}
		}
	}
}

**Expected behavior**
Record should be stored into database

**Screenshots/Stacktrace**
System.NullReferenceException: Object reference not set to an instance of an object.
   at LiteDB.BsonValue.GetHashCode()
   at System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at LiteDBBug.Program.Main(String[] args) in C:\TFSSrc\Test\LiteDBBug\LiteDBBug\Program.cs:line 50

**Comment by seertenedos** [comment] 2020-03-30 03:31
that was the cause of my issue and has been fixed but no release made yet.
https://github.com/mbdavid/LiteDB/issues/1592#issue-588880528

**Comment by riksking** [comment] 2020-04-07 16:53
I got same error NRE.

My case

`public static void WriteToExistDb(IEnumerable<object> chunk, string pathToDb, string tableName)
        {
            using (var testDb = new LiteDatabase(pathToDb))
            {
                var col = testDb.GetCollection<object>(tableName);
                foreach (var o in chunk)
                {
                    col.Insert(o);
                }
                //col.InsertBulk(chunk);
            }
        }
`

Call method like this
`var words = new List<string>(chunk);

WriteToExistDb(words, _pathToDb, _wordsTableName);`

end got error

>    System.NullReferenceException: 'Object reference not set to an instance of an object.'
at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 48
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 33
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn) in ~\LiteDB-master\LiteDB\Engine\Engine\Transaction.cs:line 101
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 20
   at LiteDB.LiteCollection`1.Insert(T entity) in ~\LiteDB-master\LiteDB\Client\Database\Collections\Insert.cs:line 20
   at Avtomat.Utils.LiteDbDataAccess.WriteToExistDb(IEnumerable`1 chunk, String pathToDb, String tableName)

As you can see, I was build from master.

I was debug LiteDb and find that in this place

![image](https://user-images.githubusercontent.com/13674964/78696977-d21c7100-7908-11ea-8d44-4121a52a0d5e.png)

I get null in BsonDocument object.

next steps in debugger

![image](https://user-images.githubusercontent.com/13674964/78697247-30495400-7909-11ea-89f2-bcca8741b243.png)

**Comment by riksking** [comment] 2020-04-07 17:00
With InsertBulk?I got similar error

>   System.NullReferenceException: 'Object reference not set to an instance of an object.'
 at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 48
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 33
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn) in ~\LiteDB-master\LiteDB\Engine\Engine\Transaction.cs:line 101
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId) in ~\LiteDB-master\LiteDB\Engine\Engine\Insert.cs:line 20
   at LiteDB.LiteCollection`1.InsertBulk(IEnumerable`1 entities, Int32 batchSize) in ~\LiteDB-master\LiteDB\Client\Database\Collections\Insert.cs:line 66
   at Avtomat.Utils.LiteDbDataAccess.WriteToExistDb(IEnumerable`1 chunk, String pathToDb, String tableName)

**Comment by lbnascimento** [comment] 2020-04-07 17:54
@riksking Your issue is very different.

First of all, you're opening your collection with `GetCollection<object>`. While this is technically supported, it is not recommended: the point of `GetCollection<T>` is that you set `T` to the C# class you're trying to store (`Person`, `Customer`, `Account`...) and the mapper converts your class to a `BsonDocument` upon insertion and converts it back to `T` upon retrieval.

The error is happening because you're trying to store strings in your `LiteCollection<object>`, and the mapper doesn't know how to map a string to a `BsonDocument`.

I'm going to close this issue, since the original problem is already fixed in the master. If you have any questions, please open another issue.

**Closed by lbnascimento** 2020-04-07 17:54 UTC
Labels: bug
